// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tao
Rcpp::List tao(Rcpp::List functions, Rcpp::NumericVector startValues, std::string method, int n, Rcpp::List options);
RcppExport SEXP taoR_tao(SEXP functionsSEXP, SEXP startValuesSEXP, SEXP methodSEXP, SEXP nSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type functions(functionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type startValues(startValuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    __result = Rcpp::wrap(tao(functions, startValues, method, n, options));
    return __result;
END_RCPP
}
