# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chwirut1 <- function(objFun, startValues, k, n) {
    .Call('taoR_chwirut1', PACKAGE = 'taoR', objFun, startValues, k, n)
}

