# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Use Pounders to minimize a non-linear sum of squares problem 
#'
#' @param objFun is an R objective function that maps k parameters into n equations.
#' @param startValues is a vector with k elements
#' @param k is the number of parameters
#' @param n is the number of elements in the objective function
#' @return a list with the objective function and the final parameter values
#'
pounders <- function(objFun, startValues, k, n) {
    .Call('taoR_pounders', PACKAGE = 'taoR', objFun, startValues, k, n)
}

